name: 'CI Report'
on:
  workflow_run:
    workflows: ['CI']
    types: [completed]

permissions:
  actions: read
  checks: write

jobs:
  report:
    name: Test Report
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Create test report
        uses: ./
        with:
          artifact: test-results
          name: Workflow Report
          path: '*.xml'
          reporter: jest-junit

      - name: Create mochawesome report
        uses: ./
        if: success() || failure()
        with:
          name: Mochawesome Tests
          path: __tests__/fixtures/mochawesome-json.json
          reporter: mochawesome-json
          fail-on-error: false
