name: 'CI'
on:
  pull_request:
    paths-ignore: ['**.md']
  push:
    paths-ignore: ['**.md']
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  checks: write
    
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint
      - run: npm test

      - name: Upload test results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: __tests__/__results__/*.xml

      - name: Create test report
        uses: ./
        with:
          artifact: test-results
          name: Workflow Report
          path: '*.xml'
          reporter: jest-junit

      - name: Create mochawesome report
        uses: ./
        if: success() || failure()
        with:
          name: Mochawesome Tests
          path: __tests__/fixtures/mochawesome-json.json
          reporter: mochawesome-json
          fail-on-error: false
  