name: 'Dirty Laundry Test'
on:
  pull_request:
    paths-ignore: ['**.md']
  push:
    paths-ignore: ['**.md']
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm run lint

      - name: Create mochawesome report
        uses: ./
        id: test-report
        if: success() || failure()
        with:
          name: Mochawesome Tests
          path: __tests__/fixtures/mochawesome1-json.json
          reporter: mochawesome-json
          fail-on-error: false
